// Auto-generated by colors.py

import "package:flutter/material.dart";
import "package:flow/theme/flow_color_scheme.dart";

final FlowColorScheme shadeOfViolet = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff8600a5),
  secondary: const Color(0xfff5ccff),
  onSecondary: const Color(0xff33004f),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.82456471142964

final FlowColorScheme blissfulBerry = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xffa50086),
  secondary: const Color(0xffffccf5),
  onSecondary: const Color(0xff4f004c),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.131551048194216

final FlowColorScheme cherryPlum = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xffa50048),
  secondary: const Color(0xffffcce2),
  onSecondary: const Color(0xff4f002e),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.529257614713291

final FlowColorScheme crispChristmasCranberries = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xffa5000a),
  secondary: const Color(0xffffcccf),
  onSecondary: const Color(0xff4f0011),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.644652409710161

final FlowColorScheme burntSienna = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xffa53300),
  secondary: const Color(0xffffdbcc),
  onSecondary: const Color(0xff4f0c00),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.272019425653915

final FlowColorScheme soilOfAvagddu = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff845a00),
  secondary: const Color(0xffffefcc),
  onSecondary: const Color(0xff4f2900),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.3249027529793045

final FlowColorScheme flagGreen = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff747b00),
  secondary: const Color(0xfffbffcc),
  onSecondary: const Color(0xff4f4700),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 4.4056160670194595

final FlowColorScheme tropicana = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff457b00),
  secondary: const Color(0xffe8ffcc),
  onSecondary: const Color(0xff384f00),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 4.759500600587007

final FlowColorScheme toyCamouflage = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff177b00),
  secondary: const Color(0xffd5ffcc),
  onSecondary: const Color(0xff1b4f00),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 4.872864221074725

final FlowColorScheme spreadsheetGreen = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff007b17),
  secondary: const Color(0xffccffd5),
  onSecondary: const Color(0xff004f02),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 4.856003928836115

final FlowColorScheme tokiwaGreen = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff007b45),
  secondary: const Color(0xffccffe8),
  onSecondary: const Color(0xff004f20),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 4.816518785663914

final FlowColorScheme hydraTurquoise = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff007b73),
  secondary: const Color(0xffccfffb),
  onSecondary: const Color(0xff004f3d),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 4.6801442121694015

final FlowColorScheme peacockBlue = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff006694),
  secondary: const Color(0xffccefff),
  onSecondary: const Color(0xff00424f),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.179720075231227

final FlowColorScheme egyptianBlue = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff0033a5),
  secondary: const Color(0xffccdbff),
  onSecondary: const Color(0xff00254f),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 7.478914206842744

final FlowColorScheme bohemianBlue = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff0a00a5),
  secondary: const Color(0xffcfccff),
  onSecondary: const Color(0xff00074f),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 8.795416386639062

final FlowColorScheme spaceBattleBlue = FlowColorScheme(
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff4800a5),
  secondary: const Color(0xffe2ccff),
  onSecondary: const Color(0xff16004f),
  onPrimary: const Color(0xfff5f6fa),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 7.838426705632426

