// Auto-generated by colors.py

import "package:flutter/material.dart";
import "package:flow/theme/flow_color_scheme.dart";

final shadeOfViolet = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff8600a5),
    secondary: const Color(0xfff5ccff),
    onSecondary: const Color(0xfff5ccff),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 5.82456471142964

final blissfulBerry = FlowColorScheme(
    isDark: false,
    primary: const Color(0xffa50086),
    secondary: const Color(0xffffccf5),
    onSecondary: const Color(0xffffccf5),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 5.131551048194216

final cherryPlum = FlowColorScheme(
    isDark: false,
    primary: const Color(0xffa50048),
    secondary: const Color(0xffffcce2),
    onSecondary: const Color(0xffffcce2),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 5.529257614713291

final crispChristmasCranberries = FlowColorScheme(
    isDark: false,
    primary: const Color(0xffa5000a),
    secondary: const Color(0xffffcccf),
    onSecondary: const Color(0xffffcccf),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 5.644652409710161

final burntSienna = FlowColorScheme(
    isDark: false,
    primary: const Color(0xffa53300),
    secondary: const Color(0xffffdbcc),
    onSecondary: const Color(0xffffdbcc),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 5.272019425653915

final soilOfAvagddu = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff845a00),
    secondary: const Color(0xffffefcc),
    onSecondary: const Color(0xffffefcc),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 5.3249027529793045

final flagGreen = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff747b00),
    secondary: const Color(0xfffbffcc),
    onSecondary: const Color(0xfffbffcc),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 4.4056160670194595

final tropicana = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff457b00),
    secondary: const Color(0xffe8ffcc),
    onSecondary: const Color(0xffe8ffcc),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 4.759500600587007

final toyCamouflage = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff177b00),
    secondary: const Color(0xffd5ffcc),
    onSecondary: const Color(0xffd5ffcc),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 4.872864221074725

final spreadsheetGreen = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff007b17),
    secondary: const Color(0xffccffd5),
    onSecondary: const Color(0xffccffd5),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 4.856003928836115

final tokiwaGreen = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff007b45),
    secondary: const Color(0xffccffe8),
    onSecondary: const Color(0xffccffe8),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 4.816518785663914

final hydraTurquoise = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff007b73),
    secondary: const Color(0xffccfffb),
    onSecondary: const Color(0xffccfffb),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 4.6801442121694015

final peacockBlue = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff006694),
    secondary: const Color(0xffccefff),
    onSecondary: const Color(0xffccefff),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 5.179720075231227

final egyptianBlue = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff0033a5),
    secondary: const Color(0xffccdbff),
    onSecondary: const Color(0xffccdbff),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 7.478914206842744

final bohemianBlue = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff0a00a5),
    secondary: const Color(0xffcfccff),
    onSecondary: const Color(0xffcfccff),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 8.795416386639062

final spaceBattleBlue = FlowColorScheme(
    isDark: false,
    primary: const Color(0xff4800a5),
    secondary: const Color(0xffe2ccff),
    onSecondary: const Color(0xffe2ccff),
    onPrimary: const Color(0xfff5f6fa),
    customColors: FlowCustomColors(
      income: Color(0xFF32CC70),
      expense: Color(0xFFFF4040),
      semi: Color(0xFF6A666D),
    ),
); // contrast: 7.838426705632426

