final Map<String, String> themeNames = {
  // LIGHT
  "defaultLightBase": "Flow - Shade of Violet",
  "shadeOfViolet": "Flow - Shade of Violet",
  "blissfulBerry": "Flow - Blissful Berry",
  "cherryPlum": "Flow - Cherry Plum",
  "crispChristmasCranberries": "Flow - Crisp Christmas Cranberries",
  "burntSienna": "Flow - Burnt Sienna",
  "soilOfAvagddu": "Flow - Soil of Avagddu",
  "flagGreen": "Flow - Flag Green",
  "tropicana": "Flow - Tropicana",
  "toyCamouflage": "Flow - Toy Camouflage",
  "spreadsheetGreen": "Flow - Spreadsheet Green",
  "tokiwaGreen": "Flow - Tokiwa Green",
  "hydraTurquoise": "Flow - Hydra Turquoise",
  "peacockBlue": "Flow - Peacock Blue",
  "egyptianBlue": "Flow - Egyptian Blue",
  "bohemianBlue": "Flow - Bohemian Blue",
  "spaceBattleBlue": "Flow - Space Battle Blue",

  // DARK
  "defaultDarkBase": "Flow - Electric Lavender",
  "electricLavender": "Flow - Electric Lavender",
  "pinkQuartz": "Flow - Pink Quartz",
  "cottonCandy": "Flow - Cotton Candy",
  "piglet": "Flow - Piglet",
  "simplyDelicious": "Flow - Simply Delicious",
  "creamyApricot": "Flow - Creamy Apricot",
  "yellYellow": "Flow - Yell Yellow",
  "fallGreen": "Flow - Fall Green",
  "frostedMintHills": "Flow - Frosted Mint Hills",
  "coastalTrim": "Flow - Coastal Trim",
  "seafairGreen": "Flow - Seafair Green",
  "crushedIce": "Flow - Crushed Ice",
  "iceEffect": "Flow - Ice Effect",
  "arcLight": "Flow - Arc Light",
  "driedLilac": "Flow - Dried Lilac",
  "neonBoneyard": "Flow - Neon Boneyard",

  // OLED
  "defaultOledBase": "Flow - Electric Lavender (OLED)",
  "electricLavenderOled": "Flow - Electric Lavender (OLED)",
  "pinkQuartzOled": "Flow - Pink Quartz (OLED)",
  "cottonCandyOled": "Flow - Cotton Candy (OLED)",
  "pigletOled": "Flow - Piglet (OLED)",
  "simplyDeliciousOled": "Flow - Simply Delicious (OLED)",
  "creamyApricotOled": "Flow - Creamy Apricot (OLED)",
  "yellYellowOled": "Flow - Yell Yellow (OLED)",
  "fallGreenOled": "Flow - Fall Green (OLED)",
  "frostedMintHillsOled": "Flow - Frosted Mint Hills (OLED)",
  "coastalTrimOled": "Flow - Coastal Trim (OLED)",
  "seafairGreenOled": "Flow - Seafair Green (OLED)",
  "crushedIceOled": "Flow - Crushed Ice (OLED)",
  "iceEffectOled": "Flow - Ice Effect (OLED)",
  "arcLightOled": "Flow - Arc Light (OLED)",
  "driedLilacOled": "Flow - Dried Lilac (OLED)",
  "neonBoneyardOled": "Flow - Neon Boneyard (OLED)",

  // Standalones
  "palenight": "Material - Palenight",

  // Catppuccin Latte
  "catppucinFlamingoLatte": "Catpuccin - Flamingo (Latte)",
  "catppucinMauveLatte": "Catpuccin - Mauve (Latte)",
  "catppucinRedLatte": "Catpuccin - Red (Latte)",
  "catppucinPeachLatte": "Catpuccin - Peach (Latte)",
  "catppucinGreenLatte": "Catpuccin - Green (Latte)",
  "catppucinSkyLatte": "Catpuccin - Sky (Latte)",
  "catppucinBlueLatte": "Catpuccin - Blue (Latte)",

  // Catppuccin Frappé
  "catppucinFlamingoFrappe": "Catpuccin - Flamingo (Frappé)",
  "catppucinMauveFrappe": "Catpuccin - Mauve (Frappé)",
  "catppucinRedFrappe": "Catpuccin - Red (Frappé)",
  "catppucinPeachFrappe": "Catpuccin - Peach (Frappé)",
  "catppucinGreenFrappe": "Catpuccin - Green (Frappé)",
  "catppucinSkyFrappe": "Catpuccin - Sky (Frappé)",
  "catppucinBlueFrappe": "Catpuccin - Blue (Frappé)",

  // Catppuccin Macchiato
  "catppucinFlamingoMacchiato": "Catpuccin - Flamingo (Macchiato)",
  "catppucinMauveMacchiato": "Catpuccin - Mauve (Macchiato)",
  "catppucinRedMacchiato": "Catpuccin - Red (Macchiato)",
  "catppucinPeachMacchiato": "Catpuccin - Peach (Macchiato)",
  "catppucinGreenMacchiato": "Catpuccin - Green (Macchiato)",
  "catppucinSkyMacchiato": "Catpuccin - Sky (Macchiato)",
  "catppucinBlueMacchiato": "Catpuccin - Blue (Macchiato)",

  // Catppuccin Mocha
  "catppucinFlamingoMocha": "Catpuccin - Flamingo (Mocha)",
  "catppucinMauveMocha": "Catpuccin - Mauve (Mocha)",
  "catppucinRedMocha": "Catpuccin - Red (Mocha)",
  "catppucinPeachMocha": "Catpuccin - Peach (Mocha)",
  "catppucinGreenMocha": "Catpuccin - Green (Mocha)",
  "catppucinSkyMocha": "Catpuccin - Sky (Mocha)",
  "catppucinBlueMocha": "Catpuccin - Blue (Mocha)",
};
