final Map<String, String> themeNames = {
  // LIGHT
  "defaultLightBase": "Flow - Shade of Violet",
  "shadeOfViolet": "Flow - Shade of Violet",
  "blissfulBerry": "Flow - Blissful Berry",
  "cherryPlum": "Flow - Cherry Plum",
  "crispChristmasCranberries": "Flow - Crisp Christmas Cranberries",
  "burntSienna": "Flow - Burnt Sienna",
  "soilOfAvagddu": "Flow - Soil of Avagddu",
  "flagGreen": "Flow - Flag Green",
  "tropicana": "Flow - Tropicana",
  "toyCamouflage": "Flow - Toy Camouflage",
  "spreadsheetGreen": "Flow - Spreadsheet Green",
  "tokiwaGreen": "Flow - Tokiwa Green",
  "hydraTurquoise": "Flow - Hydra Turquoise",
  "peacockBlue": "Flow - Peacock Blue",
  "egyptianBlue": "Flow - Egyptian Blue",
  "bohemianBlue": "Flow - Bohemian Blue",
  "spaceBattleBlue": "Flow - Space Battle Blue",

  // DARK
  "defaultDarkBase": "Flow - Electric Lavender",
  "electricLavender": "Flow - Electric Lavender",
  "pinkQuartz": "Flow - Pink Quartz",
  "cottonCandy": "Flow - Cotton Candy",
  "piglet": "Flow - Piglet",
  "simplyDelicious": "Flow - Simply Delicious",
  "creamyApricot": "Flow - Creamy Apricot",
  "yellYellow": "Flow - Yell Yellow",
  "fallGreen": "Flow - Fall Green",
  "frostedMintHills": "Flow - Frosted Mint Hills",
  "coastalTrim": "Flow - Coastal Trim",
  "seafairGreen": "Flow - Seafair Green",
  "crushedIce": "Flow - Crushed Ice",
  "iceEffect": "Flow - Ice Effect",
  "arcLight": "Flow - Arc Light",
  "driedLilac": "Flow - Dried Lilac",
  "neonBoneyard": "Flow - Neon Boneyard",

  // OLED
  "defaultOledBase": "Flow - Electric Lavender (OLED)",
  "electricLavenderOled": "Flow - Electric Lavender (OLED)",
  "pinkQuartzOled": "Flow - Pink Quartz (OLED)",
  "cottonCandyOled": "Flow - Cotton Candy (OLED)",
  "pigletOled": "Flow - Piglet (OLED)",
  "simplyDeliciousOled": "Flow - Simply Delicious (OLED)",
  "creamyApricotOled": "Flow - Creamy Apricot (OLED)",
  "yellYellowOled": "Flow - Yell Yellow (OLED)",
  "fallGreenOled": "Flow - Fall Green (OLED)",
  "frostedMintHillsOled": "Flow - Frosted Mint Hills (OLED)",
  "coastalTrimOled": "Flow - Coastal Trim (OLED)",
  "seafairGreenOled": "Flow - Seafair Green (OLED)",
  "crushedIceOled": "Flow - Crushed Ice (OLED)",
  "iceEffectOled": "Flow - Ice Effect (OLED)",
  "arcLightOled": "Flow - Arc Light (OLED)",
  "driedLilacOled": "Flow - Dried Lilac (OLED)",
  "neonBoneyardOled": "Flow - Neon Boneyard (OLED)",

  // Standalones
  "palenight": "Material - Palenight",

  // Catppuccin

  "catppuccinFlamingoFrappe": "Catppuccin Frappé - Flamingo",
  "catppuccinRosewaterFrappe": "Catppuccin Frappé - Rosewater",
  "catppuccinMauveFrappe": "Catppuccin Frappé - Mauve",
  "catppuccinPinkFrappe": "Catppuccin Frappé - Pink",
  "catppuccinRedFrappe": "Catppuccin Frappé - Red",
  "catppuccinMaroonFrappe": "Catppuccin Frappé - Maroon",
  "catppuccinPeachFrappe": "Catppuccin Frappé - Peach",
  "catppuccinYellowFrappe": "Catppuccin Frappé - Yellow",
  "catppuccinGreenFrappe": "Catppuccin Frappé - Green",
  "catppuccinTealFrappe": "Catppuccin Frappé - Teal",
  "catppuccinSkyFrappe": "Catppuccin Frappé - Sky",
  "catppuccinSapphireFrappe": "Catppuccin Frappé - Sapphire",
  "catppuccinBlueFrappe": "Catppuccin Frappé - Blue",
  "catppuccinLavenderFrappe": "Catppuccin Frappé - Lavender",

  "catppuccinFlamingoMacchiato": "Catppuccin Macchiato - Flamingo",
  "catppuccinRosewaterMacchiato": "Catppuccin Macchiato - Rosewater",
  "catppuccinMauveMacchiato": "Catppuccin Macchiato - Mauve",
  "catppuccinPinkMacchiato": "Catppuccin Macchiato - Pink",
  "catppuccinRedMacchiato": "Catppuccin Macchiato - Red",
  "catppuccinMaroonMacchiato": "Catppuccin Macchiato - Maroon",
  "catppuccinPeachMacchiato": "Catppuccin Macchiato - Peach",
  "catppuccinYellowMacchiato": "Catppuccin Macchiato - Yellow",
  "catppuccinGreenMacchiato": "Catppuccin Macchiato - Green",
  "catppuccinTealMacchiato": "Catppuccin Macchiato - Teal",
  "catppuccinSkyMacchiato": "Catppuccin Macchiato - Sky",
  "catppuccinSapphireMacchiato": "Catppuccin Macchiato - Sapphire",
  "catppuccinBlueMacchiato": "Catppuccin Macchiato - Blue",
  "catppuccinLavenderMacchiato": "Catppuccin Macchiato - Lavender",

  "catppuccinFlamingoMocha": "Catppuccin Mocha - Flamingo",
  "catppuccinRosewaterMocha": "Catppuccin Mocha - Rosewater",
  "catppuccinMauveMocha": "Catppuccin Mocha - Mauve",
  "catppuccinPinkMocha": "Catppuccin Mocha - Pink",
  "catppuccinRedMocha": "Catppuccin Mocha - Red",
  "catppuccinMaroonMocha": "Catppuccin Mocha - Maroon",
  "catppuccinPeachMocha": "Catppuccin Mocha - Peach",
  "catppuccinYellowMocha": "Catppuccin Mocha - Yellow",
  "catppuccinGreenMocha": "Catppuccin Mocha - Green",
  "catppuccinTealMocha": "Catppuccin Mocha - Teal",
  "catppuccinSkyMocha": "Catppuccin Mocha - Sky",
  "catppuccinSapphireMocha": "Catppuccin Mocha - Sapphire",
  "catppuccinBlueMocha": "Catppuccin Mocha - Blue",
  "catppuccinLavenderMocha": "Catppuccin Mocha - Lavender",
};
