include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true
    prefer_double_quotes: true
    type_annotate_public_apis: true
    always_use_package_imports: true
analyzer:
  exclude:
    - "example/**"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - android/**
    - ios/**
    - windows/**
    - macos/**
    - linux/**
