// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../entity/account.dart';
import '../entity/backup_entry.dart';
import '../entity/budget.dart';
import '../entity/category.dart';
import '../entity/file_attachment.dart';
import '../entity/goal.dart';
import '../entity/profile.dart';
import '../entity/recurring_transaction.dart';
import '../entity/transaction.dart';
import '../entity/transaction_filter_preset.dart';
import '../entity/transaction_tag.dart';
import '../entity/user_preferences.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1185109045851542775),
    name: 'Account',
    lastPropertyId: const obx_int.IdUid(16, 5820369881987699214),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 691229716270374342),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8773312281127696732),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1929937644746519082),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4657518713627449829),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 98438281425253729),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7523580271093772442),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4774765264550205574),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4199922829114171439),
        name: 'iconCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1464855086006613388),
        name: 'excludeFromTotalBalance',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4051834862557712608),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4032509736911472496),
        name: 'archived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2639662940928154297),
        name: 'creditLimit',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4500989952725300589),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5820369881987699214),
        name: 'colorSchemeName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'transactions',
        srcEntity: 'Transaction',
        srcField: 'account',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 649350347514211469),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(10, 8207473128907508304),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1543873184246568510),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4092645274001419169),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 4567310141724695230),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7355350125139499009),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6997289246296566376),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 2391044209964121362),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7989789340130049283),
        name: 'iconCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8207473128907508304),
        name: 'colorSchemeName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'transactions',
        srcEntity: 'Transaction',
        srcField: 'category',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3298987588431022631),
    name: 'Profile',
    lastPropertyId: const obx_int.IdUid(5, 3781626172731013526),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7051631551441750621),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 731255396614738413),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 6445110811655945444),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6455801293952865246),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5771346759499657768),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5991227438386928245),
    name: 'BackupEntry',
    lastPropertyId: const obx_int.IdUid(8, 7012537446377796117),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5752762434527855344),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8774895379662319967),
        name: 'syncModelVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5145480293665316701),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6125452647375382801),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5398904418479897232),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 85022155315718452),
        name: 'fileExt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5357777579468740615),
    name: 'Transaction',
    lastPropertyId: const obx_int.IdUid(25, 1116277179564620916),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9110098830115993878),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5969985101281949207),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 1386471796517044894),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 614756132375370358),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7728114574705964455),
        name: 'transactionDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 784468101854697419),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7213343959758309797),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5879078778613651092),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7268940743609048799),
        name: 'subtype',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4527254666523321017),
        name: 'extra',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3862476953254710135),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(13, 6668612341220351989),
        relationField: 'category',
        relationTarget: 'Category',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2468817122549060742),
        name: 'accountId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 1594637005857043935),
        relationField: 'account',
        relationTarget: 'Account',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2414941424956693997),
        name: 'categoryUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8197332672689416676),
        name: 'accountUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1785368014330843933),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 1342886807526846841),
        name: 'isPending',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6446498779494394629),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8440919020610534632),
        name: 'deletedDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 8105783725440518384),
        name: 'extraTags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 8732200258907669936),
        name: 'location',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(22, 4524862754555930046),
        hnswParams: obx_int.ModelHnswParams(dimensions: 2, distanceType: 6),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 2157597498441905857),
        name: 'tagsUuids',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 1116277179564620916),
        name: 'attachmentsUuids',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 3860846002029102487),
        name: 'tags',
        targetId: const obx_int.IdUid(13, 1815911240017711144),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 8693268912561290427),
        name: 'attachments',
        targetId: const obx_int.IdUid(15, 3741443681678089583),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 292195687144521768),
    name: 'TransactionFilterPreset',
    lastPropertyId: const obx_int.IdUid(5, 6338065131616428464),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7325981580084262187),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1400002030370846430),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(17, 1831520455871768337),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7489529238954087887),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7319274947084664022),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6338065131616428464),
        name: 'jsonTransactionFilter',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 7829328581176695647),
    name: 'UserPreferences',
    lastPropertyId: const obx_int.IdUid(30, 5353888497210708730),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5219039721355467640),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4955595750704416462),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(18, 256441942731857355),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7963585470530325390),
        name: 'combineTransfers',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 317897902492658580),
        name: 'excludeTransfersFromFlow',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4865088217867740277),
        name: 'defaultFilterPreset',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6538022804139410219),
        name: 'trashBinRetentionDays',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2985299148024776274),
        name: 'remindDailyAtRelativeSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8609498027521636604),
        name: 'useCategoryNameForUntitledTransactions',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1110624065651948179),
        name: 'autoBackupIntervalInHours',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9083345045177209971),
        name: 'transactionListTileShowCategoryName',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4693852392718311453),
        name: 'transactionListTileShowAccountForLeading',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6826663530484570285),
        name: 'enableICloudSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8617478279582680424),
        name: 'icuCurrencyFormattingPattern',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4857491171331889557),
        name: 'primaryCurrency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5034425281728425226),
        name: 'transactionButtonOrderJoined',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 5817984994810877086),
        name: 'iCloudBackupsToKeep',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 4873078044604055561),
        name: 'themeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 3170754472241464501),
        name: 'themeChangesAppIcon',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 2536977424684614223),
        name: 'changeVisuals',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 3911662458210039466),
        name: 'transactionListTileRelaxedDensity',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 1897952567667191209),
        name: 'transactionEntryFlowJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 4516202653950496157),
        name: 'primaryAccountUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 5365639887585710264),
        name: 'createTransactionsPerItemInScans',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 3978302515507676621),
        name: 'scansPendingThresholdInHours',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 4758372811016538649),
        name: 'privacyModeUponLaunch',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 7803371152939021971),
        name: 'privacyModeUponShaking',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 4843097333162455732),
        name: 'transactionListTileShowExternalSource',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 5353888497210708730),
        name: 'homePendingTransactionsTimeRangeSerialized',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 4948078457888921031),
    name: 'Budget',
    lastPropertyId: const obx_int.IdUid(9, 6886515900911773491),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8548068689938827083),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5437558016134721268),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(19, 806092094099867187),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4554850236746747495),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 473869210125712621),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(20, 8336098329051704990),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6253789882700699652),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1298695079656779768),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 801892318627771901),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(21, 7291423328418584896),
        relationField: 'category',
        relationTarget: 'Category',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4590726328503721316),
        name: 'categoryUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6886515900911773491),
        name: 'range',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 800756592587838565),
    name: 'RecurringTransaction',
    lastPropertyId: const obx_int.IdUid(11, 420551111786793892),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1478236043461226093),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2358830362322475217),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7015715332193102336),
        name: 'jsonTransactionTemplate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 863784590472248880),
        name: 'range',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4856660607221068479),
        name: 'rules',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6844871043566830898),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1614599721077752206),
        name: 'disabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1604914214581454059),
        name: 'transferToAccountUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 651096412135846367),
        name: 'lastGeneratedTransactionDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 1815911240017711144),
    name: 'TransactionTag',
    lastPropertyId: const obx_int.IdUid(11, 3938547905203366311),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3148504216745320475),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 267854316046110520),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(23, 848773158592813096),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1701687991250279034),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1033466507363479834),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5151684011991355185),
        name: 'deletedDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1324427155948625680),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1336731416210755961),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7684406616909361899),
        name: 'payload',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 487976549673225350),
        name: 'iconCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3938547905203366311),
        name: 'colorSchemeName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(14, 7904423998243143112),
    name: 'Goal',
    lastPropertyId: const obx_int.IdUid(10, 3196587516305976411),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5506339622345934410),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6590369245858196692),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(24, 5428246387638285574),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8127192883640469620),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4538446564856671516),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(25, 1837035268504934837),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 102148746483304310),
        name: 'range',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1142434388520977284),
        name: 'targetBalance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2371982402833524364),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 263931570311257219),
        name: 'iconCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6660372638472601413),
        name: 'accountId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(26, 6114043135141023608),
        relationField: 'account',
        relationTarget: 'Account',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3196587516305976411),
        name: 'accountUuid',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(15, 3741443681678089583),
    name: 'FileAttachment',
    lastPropertyId: const obx_int.IdUid(6, 5739129158582967162),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8212676902786201697),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7988670171710237425),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(27, 5707692371585154920),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3240403333679753202),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4058074983882486111),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5739129158582967162),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(15, 3741443681678089583),
    lastIndexId: const obx_int.IdUid(27, 5707692371585154920),
    lastRelationId: const obx_int.IdUid(3, 8693268912561290427),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      3796819593314794683,
      2857566645668229410,
      268813570801700112,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      620570223027064518,
      4256690661297760083,
      6938078869065968115,
      1403783421127032859,
      5822272069646732572,
      3352242595820563295,
      7280484442250674290,
      7528954808630752939,
      2052151351995260526,
      2763207879596101849,
      3781626172731013526,
      4631816643044519644,
      2582035562365559834,
      1199002594005420779,
      7985125654311551623,
      7846957356397143011,
      8386618621719093135,
      3858309169442527296,
      6772806689343886062,
      8465977223650476366,
      3806574754524012859,
      8163231449257835161,
      8413544260372569748,
      5446772239174299489,
      3056128952161562633,
      2675470948342446870,
      2832069050067036408,
      7884365526573124998,
      1620591330122290687,
      6855816521444032675,
      6426832099320622373,
      4688691313482515602,
      8178664360494427777,
      9181400211872351108,
      577162958135049929,
      9125625889304953158,
      4341960036397140355,
      420551111786793892,
      3842898167150913136,
      1701734084880256388,
      2598696840666344158,
      7012537446377796117,
      6033810133674409127,
      610924910099589699,
      3063095817126288040,
      2071092278574175844,
    ],
    retiredRelationUids: const [552720950599490473],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Account: obx_int.EntityDefinition<Account>(
      model: _entities[0],
      toOneRelations: (Account object) => [],
      toManyRelations: (Account object) => {
        obx_int.RelInfo<Transaction>.toOneBacklink(
          11,
          object.id,
          (Transaction srcObject) => srcObject.account,
        ): object.transactions,
      },
      getId: (Account object) => object.id,
      setId: (Account object, int id) {
        object.id = id;
      },
      objectToFB: (Account object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final currencyOffset = fbb.writeString(object.currency);
        final iconCodeOffset = fbb.writeString(object.iconCode);
        final typeOffset = fbb.writeString(object.type);
        final colorSchemeNameOffset = object.colorSchemeName == null
            ? null
            : fbb.writeString(object.colorSchemeName!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, currencyOffset);
        fbb.addOffset(6, iconCodeOffset);
        fbb.addBool(9, object.excludeFromTotalBalance);
        fbb.addInt64(10, object.sortOrder);
        fbb.addBool(11, object.archived);
        fbb.addFloat64(12, object.creditLimit);
        fbb.addOffset(14, typeOffset);
        fbb.addOffset(15, colorSchemeNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final iconCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final creditLimitParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final colorSchemeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final excludeFromTotalBalanceParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final archivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object =
            Account(
                id: idParam,
                name: nameParam,
                currency: currencyParam,
                iconCode: iconCodeParam,
                creditLimit: creditLimitParam,
                colorSchemeName: colorSchemeNameParam,
                excludeFromTotalBalance: excludeFromTotalBalanceParam,
                archived: archivedParam,
                sortOrder: sortOrderParam,
                type: typeParam,
                createdDate: createdDateParam,
              )
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '');
        obx_int.InternalToManyAccess.setRelInfo<Account>(
          object.transactions,
          store,
          obx_int.RelInfo<Transaction>.toOneBacklink(
            11,
            object.id,
            (Transaction srcObject) => srcObject.account,
          ),
        );
        return object;
      },
    ),
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[1],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {
        obx_int.RelInfo<Transaction>.toOneBacklink(
          10,
          object.id,
          (Transaction srcObject) => srcObject.category,
        ): object.transactions,
      },
      getId: (Category object) => object.id,
      setId: (Category object, int id) {
        object.id = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final iconCodeOffset = fbb.writeString(object.iconCode);
        final colorSchemeNameOffset = object.colorSchemeName == null
            ? null
            : fbb.writeString(object.colorSchemeName!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(5, iconCodeOffset);
        fbb.addOffset(9, colorSchemeNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final iconCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final colorSchemeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object =
            Category(
                id: idParam,
                name: nameParam,
                iconCode: iconCodeParam,
                createdDate: createdDateParam,
                colorSchemeName: colorSchemeNameParam,
              )
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '');
        obx_int.InternalToManyAccess.setRelInfo<Category>(
          object.transactions,
          store,
          obx_int.RelInfo<Transaction>.toOneBacklink(
            10,
            object.id,
            (Transaction srcObject) => srcObject.category,
          ),
        );
        return object;
      },
    ),
    Profile: obx_int.EntityDefinition<Profile>(
      model: _entities[2],
      toOneRelations: (Profile object) => [],
      toManyRelations: (Profile object) => {},
      getId: (Profile object) => object.id,
      setId: (Profile object, int id) {
        object.id = id;
      },
      objectToFB: (Profile object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.createdDate.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object =
            Profile(id: idParam, createdDate: createdDateParam, name: nameParam)
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '');

        return object;
      },
    ),
    BackupEntry: obx_int.EntityDefinition<BackupEntry>(
      model: _entities[3],
      toOneRelations: (BackupEntry object) => [],
      toManyRelations: (BackupEntry object) => {},
      getId: (BackupEntry object) => object.id,
      setId: (BackupEntry object, int id) {
        object.id = id;
      },
      objectToFB: (BackupEntry object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final typeOffset = fbb.writeString(object.type);
        final fileExtOffset = fbb.writeString(object.fileExt);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.syncModelVersion);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(3, filePathOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addOffset(5, fileExtOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final syncModelVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final fileExtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = BackupEntry(
          id: idParam,
          filePath: filePathParam,
          createdDate: createdDateParam,
          syncModelVersion: syncModelVersionParam,
          type: typeParam,
          fileExt: fileExtParam,
        );

        return object;
      },
    ),
    Transaction: obx_int.EntityDefinition<Transaction>(
      model: _entities[4],
      toOneRelations: (Transaction object) => [object.category, object.account],
      toManyRelations: (Transaction object) => {
        obx_int.RelInfo<Transaction>.toMany(1, object.id): object.tags,
        obx_int.RelInfo<Transaction>.toMany(3, object.id): object.attachments,
      },
      getId: (Transaction object) => object.id,
      setId: (Transaction object, int id) {
        object.id = id;
      },
      objectToFB: (Transaction object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final currencyOffset = fbb.writeString(object.currency);
        final subtypeOffset = object.subtype == null
            ? null
            : fbb.writeString(object.subtype!);
        final extraOffset = object.extra == null
            ? null
            : fbb.writeString(object.extra!);
        final categoryUuidOffset = object.categoryUuid == null
            ? null
            : fbb.writeString(object.categoryUuid!);
        final accountUuidOffset = object.accountUuid == null
            ? null
            : fbb.writeString(object.accountUuid!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final extraTagsOffset = fbb.writeList(
          object.extraTags.map(fbb.writeString).toList(growable: false),
        );
        final locationOffset = object.location == null
            ? null
            : fbb.writeListFloat32(object.location!);
        final tagsUuidsOffset = object.tagsUuids == null
            ? null
            : fbb.writeList(
                object.tagsUuids!.map(fbb.writeString).toList(growable: false),
              );
        final attachmentsUuidsOffset = object.attachmentsUuids == null
            ? null
            : fbb.writeList(
                object.attachmentsUuids!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        fbb.startTable(26);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addInt64(3, object.transactionDate.millisecondsSinceEpoch);
        fbb.addOffset(4, titleOffset);
        fbb.addFloat64(5, object.amount);
        fbb.addOffset(6, currencyOffset);
        fbb.addOffset(7, subtypeOffset);
        fbb.addOffset(8, extraOffset);
        fbb.addInt64(9, object.category.targetId);
        fbb.addInt64(10, object.account.targetId);
        fbb.addOffset(11, categoryUuidOffset);
        fbb.addOffset(12, accountUuidOffset);
        fbb.addOffset(13, descriptionOffset);
        fbb.addBool(16, object.isPending);
        fbb.addBool(17, object.isDeleted);
        fbb.addInt64(18, object.deletedDate?.millisecondsSinceEpoch);
        fbb.addOffset(20, extraTagsOffset);
        fbb.addOffset(21, locationOffset);
        fbb.addOffset(23, tagsUuidsOffset);
        fbb.addOffset(24, attachmentsUuidsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deletedDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          40,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final subtypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final isPendingParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final locationParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final transactionDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final extraTagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 44, []);
        final object =
            Transaction(
                id: idParam,
                title: titleParam,
                description: descriptionParam,
                subtype: subtypeParam,
                isPending: isPendingParam,
                location: locationParam,
                amount: amountParam,
                currency: currencyParam,
                uuid: uuidParam,
                transactionDate: transactionDateParam,
                createdDate: createdDateParam,
                extraTags: extraTagsParam,
              )
              ..extra = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 20)
              ..categoryUuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 26)
              ..accountUuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 28)
              ..isDeleted = const fb.BoolReader().vTableGetNullable(
                buffer,
                rootOffset,
                38,
              )
              ..deletedDate = deletedDateValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(deletedDateValue)
              ..tagsUuids = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGetNullable(buffer, rootOffset, 50)
              ..attachmentsUuids = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGetNullable(buffer, rootOffset, 52);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.category.attach(store);
        object.account.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.account.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Transaction>(
          object.tags,
          store,
          obx_int.RelInfo<Transaction>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Transaction>(
          object.attachments,
          store,
          obx_int.RelInfo<Transaction>.toMany(3, object.id),
        );
        return object;
      },
    ),
    TransactionFilterPreset: obx_int.EntityDefinition<TransactionFilterPreset>(
      model: _entities[5],
      toOneRelations: (TransactionFilterPreset object) => [],
      toManyRelations: (TransactionFilterPreset object) => {},
      getId: (TransactionFilterPreset object) => object.id,
      setId: (TransactionFilterPreset object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionFilterPreset object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final jsonTransactionFilterOffset = fbb.writeString(
          object.jsonTransactionFilter,
        );
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(4, jsonTransactionFilterOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final jsonTransactionFilterParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object =
            TransactionFilterPreset(
                id: idParam,
                createdDate: createdDateParam,
                jsonTransactionFilter: jsonTransactionFilterParam,
                name: nameParam,
              )
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '');

        return object;
      },
    ),
    UserPreferences: obx_int.EntityDefinition<UserPreferences>(
      model: _entities[6],
      toOneRelations: (UserPreferences object) => [],
      toManyRelations: (UserPreferences object) => {},
      getId: (UserPreferences object) => object.id,
      setId: (UserPreferences object, int id) {
        object.id = id;
      },
      objectToFB: (UserPreferences object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final defaultFilterPresetOffset = object.defaultFilterPreset == null
            ? null
            : fbb.writeString(object.defaultFilterPreset!);
        final icuCurrencyFormattingPatternOffset =
            object.icuCurrencyFormattingPattern == null
            ? null
            : fbb.writeString(object.icuCurrencyFormattingPattern!);
        final primaryCurrencyOffset = object.primaryCurrency == null
            ? null
            : fbb.writeString(object.primaryCurrency!);
        final transactionButtonOrderJoinedOffset =
            object.transactionButtonOrderJoined == null
            ? null
            : fbb.writeString(object.transactionButtonOrderJoined!);
        final themeNameOffset = object.themeName == null
            ? null
            : fbb.writeString(object.themeName!);
        final changeVisualsOffset = object.changeVisuals == null
            ? null
            : fbb.writeString(object.changeVisuals!);
        final transactionEntryFlowJsonOffset =
            object.transactionEntryFlowJson == null
            ? null
            : fbb.writeString(object.transactionEntryFlowJson!);
        final primaryAccountUuidOffset = object.primaryAccountUuid == null
            ? null
            : fbb.writeString(object.primaryAccountUuid!);
        final homePendingTransactionsTimeRangeSerializedOffset =
            object.homePendingTransactionsTimeRangeSerialized == null
            ? null
            : fbb.writeString(
                object.homePendingTransactionsTimeRangeSerialized!,
              );
        fbb.startTable(31);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addBool(2, object.combineTransfers);
        fbb.addBool(3, object.excludeTransfersFromFlow);
        fbb.addOffset(4, defaultFilterPresetOffset);
        fbb.addInt64(5, object.trashBinRetentionDays);
        fbb.addInt64(6, object.remindDailyAtRelativeSeconds);
        fbb.addBool(7, object.useCategoryNameForUntitledTransactions);
        fbb.addInt64(9, object.autoBackupIntervalInHours);
        fbb.addBool(10, object.transactionListTileShowCategoryName);
        fbb.addBool(11, object.transactionListTileShowAccountForLeading);
        fbb.addBool(12, object.enableICloudSync);
        fbb.addOffset(13, icuCurrencyFormattingPatternOffset);
        fbb.addOffset(15, primaryCurrencyOffset);
        fbb.addOffset(16, transactionButtonOrderJoinedOffset);
        fbb.addInt64(17, object.iCloudBackupsToKeep);
        fbb.addOffset(18, themeNameOffset);
        fbb.addBool(19, object.themeChangesAppIcon);
        fbb.addOffset(20, changeVisualsOffset);
        fbb.addBool(21, object.transactionListTileRelaxedDensity);
        fbb.addOffset(22, transactionEntryFlowJsonOffset);
        fbb.addOffset(23, primaryAccountUuidOffset);
        fbb.addBool(24, object.createTransactionsPerItemInScans);
        fbb.addInt64(25, object.scansPendingThresholdInHours);
        fbb.addBool(26, object.privacyModeUponLaunch);
        fbb.addBool(27, object.privacyModeUponShaking);
        fbb.addBool(28, object.transactionListTileShowExternalSource);
        fbb.addOffset(29, homePendingTransactionsTimeRangeSerializedOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final combineTransfersParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final excludeTransfersFromFlowParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final useCategoryNameForUntitledTransactionsParam =
            const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
        final transactionListTileShowCategoryNameParam = const fb.BoolReader()
            .vTableGet(buffer, rootOffset, 24, false);
        final transactionListTileShowAccountForLeadingParam =
            const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false);
        final transactionListTileShowExternalSourceParam = const fb.BoolReader()
            .vTableGet(buffer, rootOffset, 60, false);
        final transactionListTileRelaxedDensityParam = const fb.BoolReader()
            .vTableGet(buffer, rootOffset, 46, false);
        final createTransactionsPerItemInScansParam = const fb.BoolReader()
            .vTableGet(buffer, rootOffset, 52, false);
        final scansPendingThresholdInHoursParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 54);
        final privacyModeUponLaunchParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          56,
          false,
        );
        final privacyModeUponShakingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          58,
          false,
        );
        final trashBinRetentionDaysParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 14);
        final defaultFilterPresetParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final homePendingTransactionsTimeRangeSerializedParam =
            const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 62);
        final enableICloudSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final iCloudBackupsToKeepParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 38);
        final autoBackupIntervalInHoursParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 22);
        final icuCurrencyFormattingPatternParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final primaryCurrencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final primaryAccountUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final transactionButtonOrderJoinedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final remindDailyAtRelativeSecondsParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final themeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final transactionEntryFlowJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final themeChangesAppIconParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          42,
          false,
        );
        final object =
            UserPreferences(
                id: idParam,
                combineTransfers: combineTransfersParam,
                excludeTransfersFromFlow: excludeTransfersFromFlowParam,
                useCategoryNameForUntitledTransactions:
                    useCategoryNameForUntitledTransactionsParam,
                transactionListTileShowCategoryName:
                    transactionListTileShowCategoryNameParam,
                transactionListTileShowAccountForLeading:
                    transactionListTileShowAccountForLeadingParam,
                transactionListTileShowExternalSource:
                    transactionListTileShowExternalSourceParam,
                transactionListTileRelaxedDensity:
                    transactionListTileRelaxedDensityParam,
                createTransactionsPerItemInScans:
                    createTransactionsPerItemInScansParam,
                scansPendingThresholdInHours: scansPendingThresholdInHoursParam,
                privacyModeUponLaunch: privacyModeUponLaunchParam,
                privacyModeUponShaking: privacyModeUponShakingParam,
                trashBinRetentionDays: trashBinRetentionDaysParam,
                defaultFilterPreset: defaultFilterPresetParam,
                homePendingTransactionsTimeRangeSerialized:
                    homePendingTransactionsTimeRangeSerializedParam,
                enableICloudSync: enableICloudSyncParam,
                iCloudBackupsToKeep: iCloudBackupsToKeepParam,
                autoBackupIntervalInHours: autoBackupIntervalInHoursParam,
                icuCurrencyFormattingPattern: icuCurrencyFormattingPatternParam,
                primaryCurrency: primaryCurrencyParam,
                primaryAccountUuid: primaryAccountUuidParam,
                transactionButtonOrderJoined: transactionButtonOrderJoinedParam,
                remindDailyAtRelativeSeconds: remindDailyAtRelativeSecondsParam,
                themeName: themeNameParam,
                transactionEntryFlowJson: transactionEntryFlowJsonParam,
                themeChangesAppIcon: themeChangesAppIconParam,
              )
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '')
              ..changeVisuals = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 44);

        return object;
      },
    ),
    Budget: obx_int.EntityDefinition<Budget>(
      model: _entities[7],
      toOneRelations: (Budget object) => [object.category],
      toManyRelations: (Budget object) => {},
      getId: (Budget object) => object.id,
      setId: (Budget object, int id) {
        object.id = id;
      },
      objectToFB: (Budget object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final currencyOffset = fbb.writeString(object.currency);
        final categoryUuidOffset = object.categoryUuid == null
            ? null
            : fbb.writeString(object.categoryUuid!);
        final rangeOffset = fbb.writeString(object.range);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(3, nameOffset);
        fbb.addFloat64(4, object.amount);
        fbb.addOffset(5, currencyOffset);
        fbb.addInt64(6, object.category.targetId);
        fbb.addOffset(7, categoryUuidOffset);
        fbb.addOffset(8, rangeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final rangeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object =
            Budget(
                id: idParam,
                name: nameParam,
                amount: amountParam,
                currency: currencyParam,
                range: rangeParam,
                createdDate: createdDateParam,
              )
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '')
              ..categoryUuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 18);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
    RecurringTransaction: obx_int.EntityDefinition<RecurringTransaction>(
      model: _entities[8],
      toOneRelations: (RecurringTransaction object) => [],
      toManyRelations: (RecurringTransaction object) => {},
      getId: (RecurringTransaction object) => object.id,
      setId: (RecurringTransaction object, int id) {
        object.id = id;
      },
      objectToFB: (RecurringTransaction object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final jsonTransactionTemplateOffset = fbb.writeString(
          object.jsonTransactionTemplate,
        );
        final rangeOffset = fbb.writeString(object.range);
        final rulesOffset = fbb.writeList(
          object.rules.map(fbb.writeString).toList(growable: false),
        );
        final transferToAccountUuidOffset = object.transferToAccountUuid == null
            ? null
            : fbb.writeString(object.transferToAccountUuid!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, jsonTransactionTemplateOffset);
        fbb.addOffset(3, rangeOffset);
        fbb.addOffset(4, rulesOffset);
        fbb.addInt64(5, object.createdDate.millisecondsSinceEpoch);
        fbb.addBool(6, object.disabled);
        fbb.addOffset(8, transferToAccountUuidOffset);
        fbb.addInt64(
          9,
          object.lastGeneratedTransactionDate?.millisecondsSinceEpoch,
        );
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastGeneratedTransactionDateValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 22);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final disabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final rulesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final jsonTransactionTemplateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final rangeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final transferToAccountUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final lastGeneratedTransactionDateParam =
            lastGeneratedTransactionDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                lastGeneratedTransactionDateValue,
              );
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = RecurringTransaction(
          id: idParam,
          disabled: disabledParam,
          rules: rulesParam,
          jsonTransactionTemplate: jsonTransactionTemplateParam,
          range: rangeParam,
          transferToAccountUuid: transferToAccountUuidParam,
          lastGeneratedTransactionDate: lastGeneratedTransactionDateParam,
          createdDate: createdDateParam,
          uuid: uuidParam,
        );

        return object;
      },
    ),
    TransactionTag: obx_int.EntityDefinition<TransactionTag>(
      model: _entities[9],
      toOneRelations: (TransactionTag object) => [],
      toManyRelations: (TransactionTag object) => {},
      getId: (TransactionTag object) => object.id,
      setId: (TransactionTag object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionTag object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        final payloadOffset = object.payload == null
            ? null
            : fbb.writeString(object.payload!);
        final iconCodeOffset = object.iconCode == null
            ? null
            : fbb.writeString(object.iconCode!);
        final colorSchemeNameOffset = object.colorSchemeName == null
            ? null
            : fbb.writeString(object.colorSchemeName!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addBool(3, object.isDeleted);
        fbb.addInt64(4, object.deletedDate?.millisecondsSinceEpoch);
        fbb.addOffset(5, titleOffset);
        fbb.addOffset(6, typeOffset);
        fbb.addOffset(7, payloadOffset);
        fbb.addOffset(8, iconCodeOffset);
        fbb.addOffset(10, colorSchemeNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deletedDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final deletedDateParam = deletedDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(deletedDateValue);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final payloadParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final iconCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final colorSchemeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object = TransactionTag(
          id: idParam,
          uuid: uuidParam,
          createdDate: createdDateParam,
          isDeleted: isDeletedParam,
          deletedDate: deletedDateParam,
          title: titleParam,
          type: typeParam,
          payload: payloadParam,
          iconCode: iconCodeParam,
          colorSchemeName: colorSchemeNameParam,
        );

        return object;
      },
    ),
    Goal: obx_int.EntityDefinition<Goal>(
      model: _entities[10],
      toOneRelations: (Goal object) => [object.account],
      toManyRelations: (Goal object) => {},
      getId: (Goal object) => object.id,
      setId: (Goal object, int id) {
        object.id = id;
      },
      objectToFB: (Goal object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final rangeOffset = object.range == null
            ? null
            : fbb.writeString(object.range!);
        final currencyOffset = fbb.writeString(object.currency);
        final iconCodeOffset = object.iconCode == null
            ? null
            : fbb.writeString(object.iconCode!);
        final accountUuidOffset = object.accountUuid == null
            ? null
            : fbb.writeString(object.accountUuid!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, rangeOffset);
        fbb.addFloat64(5, object.targetBalance);
        fbb.addOffset(6, currencyOffset);
        fbb.addOffset(7, iconCodeOffset);
        fbb.addInt64(8, object.account.targetId);
        fbb.addOffset(9, accountUuidOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final targetBalanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final rangeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final iconCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object =
            Goal(
                id: idParam,
                name: nameParam,
                targetBalance: targetBalanceParam,
                currency: currencyParam,
                range: rangeParam,
                iconCode: iconCodeParam,
                createdDate: createdDateParam,
              )
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '')
              ..accountUuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 22);
        object.account.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.account.attach(store);
        return object;
      },
    ),
    FileAttachment: obx_int.EntityDefinition<FileAttachment>(
      model: _entities[11],
      toOneRelations: (FileAttachment object) => [],
      toManyRelations: (FileAttachment object) => {},
      getId: (FileAttachment object) => object.id,
      setId: (FileAttachment object, int id) {
        object.id = id;
      },
      objectToFB: (FileAttachment object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final filePathOffset = fbb.writeString(object.filePath);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.createdDate.millisecondsSinceEpoch);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(5, filePathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object =
            FileAttachment(
                id: idParam,
                name: nameParam,
                filePath: filePathParam,
                createdDate: createdDateParam,
              )
              ..uuid = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Account] entity fields to define ObjectBox queries.
class Account_ {
  /// See [Account.id].
  static final id = obx.QueryIntegerProperty<Account>(
    _entities[0].properties[0],
  );

  /// See [Account.uuid].
  static final uuid = obx.QueryStringProperty<Account>(
    _entities[0].properties[1],
  );

  /// See [Account.createdDate].
  static final createdDate = obx.QueryDateProperty<Account>(
    _entities[0].properties[2],
  );

  /// See [Account.name].
  static final name = obx.QueryStringProperty<Account>(
    _entities[0].properties[3],
  );

  /// See [Account.currency].
  static final currency = obx.QueryStringProperty<Account>(
    _entities[0].properties[4],
  );

  /// See [Account.iconCode].
  static final iconCode = obx.QueryStringProperty<Account>(
    _entities[0].properties[5],
  );

  /// See [Account.excludeFromTotalBalance].
  static final excludeFromTotalBalance = obx.QueryBooleanProperty<Account>(
    _entities[0].properties[6],
  );

  /// See [Account.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<Account>(
    _entities[0].properties[7],
  );

  /// See [Account.archived].
  static final archived = obx.QueryBooleanProperty<Account>(
    _entities[0].properties[8],
  );

  /// See [Account.creditLimit].
  static final creditLimit = obx.QueryDoubleProperty<Account>(
    _entities[0].properties[9],
  );

  /// See [Account.type].
  static final type = obx.QueryStringProperty<Account>(
    _entities[0].properties[10],
  );

  /// See [Account.colorSchemeName].
  static final colorSchemeName = obx.QueryStringProperty<Account>(
    _entities[0].properties[11],
  );

  /// see [Account.transactions]
  static final transactions = obx.QueryBacklinkToMany<Transaction, Account>(
    Transaction_.account,
  );
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id = obx.QueryIntegerProperty<Category>(
    _entities[1].properties[0],
  );

  /// See [Category.uuid].
  static final uuid = obx.QueryStringProperty<Category>(
    _entities[1].properties[1],
  );

  /// See [Category.createdDate].
  static final createdDate = obx.QueryDateProperty<Category>(
    _entities[1].properties[2],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[1].properties[3],
  );

  /// See [Category.iconCode].
  static final iconCode = obx.QueryStringProperty<Category>(
    _entities[1].properties[4],
  );

  /// See [Category.colorSchemeName].
  static final colorSchemeName = obx.QueryStringProperty<Category>(
    _entities[1].properties[5],
  );

  /// see [Category.transactions]
  static final transactions = obx.QueryBacklinkToMany<Transaction, Category>(
    Transaction_.category,
  );
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.id].
  static final id = obx.QueryIntegerProperty<Profile>(
    _entities[2].properties[0],
  );

  /// See [Profile.uuid].
  static final uuid = obx.QueryStringProperty<Profile>(
    _entities[2].properties[1],
  );

  /// See [Profile.name].
  static final name = obx.QueryStringProperty<Profile>(
    _entities[2].properties[2],
  );

  /// See [Profile.createdDate].
  static final createdDate = obx.QueryDateProperty<Profile>(
    _entities[2].properties[3],
  );
}

/// [BackupEntry] entity fields to define ObjectBox queries.
class BackupEntry_ {
  /// See [BackupEntry.id].
  static final id = obx.QueryIntegerProperty<BackupEntry>(
    _entities[3].properties[0],
  );

  /// See [BackupEntry.syncModelVersion].
  static final syncModelVersion = obx.QueryIntegerProperty<BackupEntry>(
    _entities[3].properties[1],
  );

  /// See [BackupEntry.createdDate].
  static final createdDate = obx.QueryDateProperty<BackupEntry>(
    _entities[3].properties[2],
  );

  /// See [BackupEntry.filePath].
  static final filePath = obx.QueryStringProperty<BackupEntry>(
    _entities[3].properties[3],
  );

  /// See [BackupEntry.type].
  static final type = obx.QueryStringProperty<BackupEntry>(
    _entities[3].properties[4],
  );

  /// See [BackupEntry.fileExt].
  static final fileExt = obx.QueryStringProperty<BackupEntry>(
    _entities[3].properties[5],
  );
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.id].
  static final id = obx.QueryIntegerProperty<Transaction>(
    _entities[4].properties[0],
  );

  /// See [Transaction.uuid].
  static final uuid = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[1],
  );

  /// See [Transaction.createdDate].
  static final createdDate = obx.QueryDateProperty<Transaction>(
    _entities[4].properties[2],
  );

  /// See [Transaction.transactionDate].
  static final transactionDate = obx.QueryDateProperty<Transaction>(
    _entities[4].properties[3],
  );

  /// See [Transaction.title].
  static final title = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[4],
  );

  /// See [Transaction.amount].
  static final amount = obx.QueryDoubleProperty<Transaction>(
    _entities[4].properties[5],
  );

  /// See [Transaction.currency].
  static final currency = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[6],
  );

  /// See [Transaction.subtype].
  static final subtype = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[7],
  );

  /// See [Transaction.extra].
  static final extra = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[8],
  );

  /// See [Transaction.category].
  static final category = obx.QueryRelationToOne<Transaction, Category>(
    _entities[4].properties[9],
  );

  /// See [Transaction.account].
  static final account = obx.QueryRelationToOne<Transaction, Account>(
    _entities[4].properties[10],
  );

  /// See [Transaction.categoryUuid].
  static final categoryUuid = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[11],
  );

  /// See [Transaction.accountUuid].
  static final accountUuid = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[12],
  );

  /// See [Transaction.description].
  static final description = obx.QueryStringProperty<Transaction>(
    _entities[4].properties[13],
  );

  /// See [Transaction.isPending].
  static final isPending = obx.QueryBooleanProperty<Transaction>(
    _entities[4].properties[14],
  );

  /// See [Transaction.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Transaction>(
    _entities[4].properties[15],
  );

  /// See [Transaction.deletedDate].
  static final deletedDate = obx.QueryDateProperty<Transaction>(
    _entities[4].properties[16],
  );

  /// See [Transaction.extraTags].
  static final extraTags = obx.QueryStringVectorProperty<Transaction>(
    _entities[4].properties[17],
  );

  /// See [Transaction.location].
  static final location = obx.QueryHnswProperty<Transaction>(
    _entities[4].properties[18],
  );

  /// See [Transaction.tagsUuids].
  static final tagsUuids = obx.QueryStringVectorProperty<Transaction>(
    _entities[4].properties[19],
  );

  /// See [Transaction.attachmentsUuids].
  static final attachmentsUuids = obx.QueryStringVectorProperty<Transaction>(
    _entities[4].properties[20],
  );

  /// see [Transaction.tags]
  static final tags = obx.QueryRelationToMany<Transaction, TransactionTag>(
    _entities[4].relations[0],
  );

  /// see [Transaction.attachments]
  static final attachments =
      obx.QueryRelationToMany<Transaction, FileAttachment>(
        _entities[4].relations[1],
      );
}

/// [TransactionFilterPreset] entity fields to define ObjectBox queries.
class TransactionFilterPreset_ {
  /// See [TransactionFilterPreset.id].
  static final id = obx.QueryIntegerProperty<TransactionFilterPreset>(
    _entities[5].properties[0],
  );

  /// See [TransactionFilterPreset.uuid].
  static final uuid = obx.QueryStringProperty<TransactionFilterPreset>(
    _entities[5].properties[1],
  );

  /// See [TransactionFilterPreset.name].
  static final name = obx.QueryStringProperty<TransactionFilterPreset>(
    _entities[5].properties[2],
  );

  /// See [TransactionFilterPreset.createdDate].
  static final createdDate = obx.QueryDateProperty<TransactionFilterPreset>(
    _entities[5].properties[3],
  );

  /// See [TransactionFilterPreset.jsonTransactionFilter].
  static final jsonTransactionFilter =
      obx.QueryStringProperty<TransactionFilterPreset>(
        _entities[5].properties[4],
      );
}

/// [UserPreferences] entity fields to define ObjectBox queries.
class UserPreferences_ {
  /// See [UserPreferences.id].
  static final id = obx.QueryIntegerProperty<UserPreferences>(
    _entities[6].properties[0],
  );

  /// See [UserPreferences.uuid].
  static final uuid = obx.QueryStringProperty<UserPreferences>(
    _entities[6].properties[1],
  );

  /// See [UserPreferences.combineTransfers].
  static final combineTransfers = obx.QueryBooleanProperty<UserPreferences>(
    _entities[6].properties[2],
  );

  /// See [UserPreferences.excludeTransfersFromFlow].
  static final excludeTransfersFromFlow =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[3]);

  /// See [UserPreferences.defaultFilterPreset].
  static final defaultFilterPreset = obx.QueryStringProperty<UserPreferences>(
    _entities[6].properties[4],
  );

  /// See [UserPreferences.trashBinRetentionDays].
  static final trashBinRetentionDays =
      obx.QueryIntegerProperty<UserPreferences>(_entities[6].properties[5]);

  /// See [UserPreferences.remindDailyAtRelativeSeconds].
  static final remindDailyAtRelativeSeconds =
      obx.QueryIntegerProperty<UserPreferences>(_entities[6].properties[6]);

  /// See [UserPreferences.useCategoryNameForUntitledTransactions].
  static final useCategoryNameForUntitledTransactions =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[7]);

  /// See [UserPreferences.autoBackupIntervalInHours].
  static final autoBackupIntervalInHours =
      obx.QueryIntegerProperty<UserPreferences>(_entities[6].properties[8]);

  /// See [UserPreferences.transactionListTileShowCategoryName].
  static final transactionListTileShowCategoryName =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[9]);

  /// See [UserPreferences.transactionListTileShowAccountForLeading].
  static final transactionListTileShowAccountForLeading =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[10]);

  /// See [UserPreferences.enableICloudSync].
  static final enableICloudSync = obx.QueryBooleanProperty<UserPreferences>(
    _entities[6].properties[11],
  );

  /// See [UserPreferences.icuCurrencyFormattingPattern].
  static final icuCurrencyFormattingPattern =
      obx.QueryStringProperty<UserPreferences>(_entities[6].properties[12]);

  /// See [UserPreferences.primaryCurrency].
  static final primaryCurrency = obx.QueryStringProperty<UserPreferences>(
    _entities[6].properties[13],
  );

  /// See [UserPreferences.transactionButtonOrderJoined].
  static final transactionButtonOrderJoined =
      obx.QueryStringProperty<UserPreferences>(_entities[6].properties[14]);

  /// See [UserPreferences.iCloudBackupsToKeep].
  static final iCloudBackupsToKeep = obx.QueryIntegerProperty<UserPreferences>(
    _entities[6].properties[15],
  );

  /// See [UserPreferences.themeName].
  static final themeName = obx.QueryStringProperty<UserPreferences>(
    _entities[6].properties[16],
  );

  /// See [UserPreferences.themeChangesAppIcon].
  static final themeChangesAppIcon = obx.QueryBooleanProperty<UserPreferences>(
    _entities[6].properties[17],
  );

  /// See [UserPreferences.changeVisuals].
  static final changeVisuals = obx.QueryStringProperty<UserPreferences>(
    _entities[6].properties[18],
  );

  /// See [UserPreferences.transactionListTileRelaxedDensity].
  static final transactionListTileRelaxedDensity =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[19]);

  /// See [UserPreferences.transactionEntryFlowJson].
  static final transactionEntryFlowJson =
      obx.QueryStringProperty<UserPreferences>(_entities[6].properties[20]);

  /// See [UserPreferences.primaryAccountUuid].
  static final primaryAccountUuid = obx.QueryStringProperty<UserPreferences>(
    _entities[6].properties[21],
  );

  /// See [UserPreferences.createTransactionsPerItemInScans].
  static final createTransactionsPerItemInScans =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[22]);

  /// See [UserPreferences.scansPendingThresholdInHours].
  static final scansPendingThresholdInHours =
      obx.QueryIntegerProperty<UserPreferences>(_entities[6].properties[23]);

  /// See [UserPreferences.privacyModeUponLaunch].
  static final privacyModeUponLaunch =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[24]);

  /// See [UserPreferences.privacyModeUponShaking].
  static final privacyModeUponShaking =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[25]);

  /// See [UserPreferences.transactionListTileShowExternalSource].
  static final transactionListTileShowExternalSource =
      obx.QueryBooleanProperty<UserPreferences>(_entities[6].properties[26]);

  /// See [UserPreferences.homePendingTransactionsTimeRangeSerialized].
  static final homePendingTransactionsTimeRangeSerialized =
      obx.QueryStringProperty<UserPreferences>(_entities[6].properties[27]);
}

/// [Budget] entity fields to define ObjectBox queries.
class Budget_ {
  /// See [Budget.id].
  static final id = obx.QueryIntegerProperty<Budget>(
    _entities[7].properties[0],
  );

  /// See [Budget.uuid].
  static final uuid = obx.QueryStringProperty<Budget>(
    _entities[7].properties[1],
  );

  /// See [Budget.createdDate].
  static final createdDate = obx.QueryDateProperty<Budget>(
    _entities[7].properties[2],
  );

  /// See [Budget.name].
  static final name = obx.QueryStringProperty<Budget>(
    _entities[7].properties[3],
  );

  /// See [Budget.amount].
  static final amount = obx.QueryDoubleProperty<Budget>(
    _entities[7].properties[4],
  );

  /// See [Budget.currency].
  static final currency = obx.QueryStringProperty<Budget>(
    _entities[7].properties[5],
  );

  /// See [Budget.category].
  static final category = obx.QueryRelationToOne<Budget, Category>(
    _entities[7].properties[6],
  );

  /// See [Budget.categoryUuid].
  static final categoryUuid = obx.QueryStringProperty<Budget>(
    _entities[7].properties[7],
  );

  /// See [Budget.range].
  static final range = obx.QueryStringProperty<Budget>(
    _entities[7].properties[8],
  );
}

/// [RecurringTransaction] entity fields to define ObjectBox queries.
class RecurringTransaction_ {
  /// See [RecurringTransaction.id].
  static final id = obx.QueryIntegerProperty<RecurringTransaction>(
    _entities[8].properties[0],
  );

  /// See [RecurringTransaction.uuid].
  static final uuid = obx.QueryStringProperty<RecurringTransaction>(
    _entities[8].properties[1],
  );

  /// See [RecurringTransaction.jsonTransactionTemplate].
  static final jsonTransactionTemplate =
      obx.QueryStringProperty<RecurringTransaction>(_entities[8].properties[2]);

  /// See [RecurringTransaction.range].
  static final range = obx.QueryStringProperty<RecurringTransaction>(
    _entities[8].properties[3],
  );

  /// See [RecurringTransaction.rules].
  static final rules = obx.QueryStringVectorProperty<RecurringTransaction>(
    _entities[8].properties[4],
  );

  /// See [RecurringTransaction.createdDate].
  static final createdDate = obx.QueryDateProperty<RecurringTransaction>(
    _entities[8].properties[5],
  );

  /// See [RecurringTransaction.disabled].
  static final disabled = obx.QueryBooleanProperty<RecurringTransaction>(
    _entities[8].properties[6],
  );

  /// See [RecurringTransaction.transferToAccountUuid].
  static final transferToAccountUuid =
      obx.QueryStringProperty<RecurringTransaction>(_entities[8].properties[7]);

  /// See [RecurringTransaction.lastGeneratedTransactionDate].
  static final lastGeneratedTransactionDate =
      obx.QueryDateProperty<RecurringTransaction>(_entities[8].properties[8]);
}

/// [TransactionTag] entity fields to define ObjectBox queries.
class TransactionTag_ {
  /// See [TransactionTag.id].
  static final id = obx.QueryIntegerProperty<TransactionTag>(
    _entities[9].properties[0],
  );

  /// See [TransactionTag.uuid].
  static final uuid = obx.QueryStringProperty<TransactionTag>(
    _entities[9].properties[1],
  );

  /// See [TransactionTag.createdDate].
  static final createdDate = obx.QueryDateProperty<TransactionTag>(
    _entities[9].properties[2],
  );

  /// See [TransactionTag.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<TransactionTag>(
    _entities[9].properties[3],
  );

  /// See [TransactionTag.deletedDate].
  static final deletedDate = obx.QueryDateProperty<TransactionTag>(
    _entities[9].properties[4],
  );

  /// See [TransactionTag.title].
  static final title = obx.QueryStringProperty<TransactionTag>(
    _entities[9].properties[5],
  );

  /// See [TransactionTag.type].
  static final type = obx.QueryStringProperty<TransactionTag>(
    _entities[9].properties[6],
  );

  /// See [TransactionTag.payload].
  static final payload = obx.QueryStringProperty<TransactionTag>(
    _entities[9].properties[7],
  );

  /// See [TransactionTag.iconCode].
  static final iconCode = obx.QueryStringProperty<TransactionTag>(
    _entities[9].properties[8],
  );

  /// See [TransactionTag.colorSchemeName].
  static final colorSchemeName = obx.QueryStringProperty<TransactionTag>(
    _entities[9].properties[9],
  );
}

/// [Goal] entity fields to define ObjectBox queries.
class Goal_ {
  /// See [Goal.id].
  static final id = obx.QueryIntegerProperty<Goal>(_entities[10].properties[0]);

  /// See [Goal.uuid].
  static final uuid = obx.QueryStringProperty<Goal>(
    _entities[10].properties[1],
  );

  /// See [Goal.createdDate].
  static final createdDate = obx.QueryDateProperty<Goal>(
    _entities[10].properties[2],
  );

  /// See [Goal.name].
  static final name = obx.QueryStringProperty<Goal>(
    _entities[10].properties[3],
  );

  /// See [Goal.range].
  static final range = obx.QueryStringProperty<Goal>(
    _entities[10].properties[4],
  );

  /// See [Goal.targetBalance].
  static final targetBalance = obx.QueryDoubleProperty<Goal>(
    _entities[10].properties[5],
  );

  /// See [Goal.currency].
  static final currency = obx.QueryStringProperty<Goal>(
    _entities[10].properties[6],
  );

  /// See [Goal.iconCode].
  static final iconCode = obx.QueryStringProperty<Goal>(
    _entities[10].properties[7],
  );

  /// See [Goal.account].
  static final account = obx.QueryRelationToOne<Goal, Account>(
    _entities[10].properties[8],
  );

  /// See [Goal.accountUuid].
  static final accountUuid = obx.QueryStringProperty<Goal>(
    _entities[10].properties[9],
  );
}

/// [FileAttachment] entity fields to define ObjectBox queries.
class FileAttachment_ {
  /// See [FileAttachment.id].
  static final id = obx.QueryIntegerProperty<FileAttachment>(
    _entities[11].properties[0],
  );

  /// See [FileAttachment.uuid].
  static final uuid = obx.QueryStringProperty<FileAttachment>(
    _entities[11].properties[1],
  );

  /// See [FileAttachment.createdDate].
  static final createdDate = obx.QueryDateProperty<FileAttachment>(
    _entities[11].properties[2],
  );

  /// See [FileAttachment.name].
  static final name = obx.QueryStringProperty<FileAttachment>(
    _entities[11].properties[3],
  );

  /// See [FileAttachment.filePath].
  static final filePath = obx.QueryStringProperty<FileAttachment>(
    _entities[11].properties[4],
  );
}
