// Auto-generated by colors.py

import "package:flow/data/flow_icon.dart";
import "package:flow/theme/flow_color_scheme.dart";
import "package:flow/theme/flow_theme_group.dart";
import "package:flutter/material.dart";
import "package:material_symbols_icons/symbols.dart";

final FlowColorScheme _defaultLightBase = FlowColorScheme(
  name: "defaultLightBase",
  isDark: false,
  surface: const Color(0xfff5f6fa),
  onSurface: const Color(0xff111111),
  primary: const Color(0xff8600a5),
  onPrimary: const Color(0xfff5f6fa),
  secondary: const Color(0xfff5ccff),
  onSecondary: const Color(0xff33004f),
  customColors: FlowCustomColors(
    income: Color(0xFF32CC70),
    expense: Color(0xFFFF4040),
    semi: Color(0xFF6A666D),
  ),
); // contrast: 5.82456471142964

final FlowThemeGroup flowLights = FlowThemeGroup(
  name: "Flow Light",
  icon: FlowIconData.icon(Symbols.light_mode_rounded),
  schemes: [
    _defaultLightBase.copyWith(
      name: "shadeOfViolet",
      iconName: "shadeOfViolet",
      primary: const Color(0xff8600a5),
      secondary: const Color(0xfff5ccff),
      onSecondary: const Color(0xff33004f),
    ),
    _defaultLightBase.copyWith(
      name: "blissfulBerry",
      iconName: "blissfulBerry",
      primary: const Color(0xffa50086),
      secondary: const Color(0xffffccf5),
      onSecondary: const Color(0xff4f004c),
    ),
    _defaultLightBase.copyWith(
      name: "cherryPlum",
      iconName: "cherryPlum",
      primary: const Color(0xffa50048),
      secondary: const Color(0xffffcce2),
      onSecondary: const Color(0xff4f002e),
    ),
    _defaultLightBase.copyWith(
      name: "crispChristmasCranberries",
      iconName: "crispChristmasCranberries",
      primary: const Color(0xffa5000a),
      secondary: const Color(0xffffcccf),
      onSecondary: const Color(0xff4f0011),
    ),
    _defaultLightBase.copyWith(
      name: "burntSienna",
      iconName: "burntSienna",
      primary: const Color(0xffa53300),
      secondary: const Color(0xffffdbcc),
      onSecondary: const Color(0xff4f0c00),
    ),
    _defaultLightBase.copyWith(
      name: "soilOfAvagddu",
      iconName: "soilOfAvagddu",
      primary: const Color(0xff845a00),
      secondary: const Color(0xffffefcc),
      onSecondary: const Color(0xff4f2900),
    ),
    _defaultLightBase.copyWith(
      name: "flagGreen",
      iconName: "flagGreen",
      primary: const Color(0xff747b00),
      secondary: const Color(0xfffbffcc),
      onSecondary: const Color(0xff4f4700),
    ),
    _defaultLightBase.copyWith(
      name: "tropicana",
      iconName: "tropicana",
      primary: const Color(0xff457b00),
      secondary: const Color(0xffe8ffcc),
      onSecondary: const Color(0xff384f00),
    ),
    _defaultLightBase.copyWith(
      name: "toyCamouflage",
      iconName: "toyCamouflage",
      primary: const Color(0xff177b00),
      secondary: const Color(0xffd5ffcc),
      onSecondary: const Color(0xff1b4f00),
    ),
    _defaultLightBase.copyWith(
      name: "spreadsheetGreen",
      iconName: "spreadsheetGreen",
      primary: const Color(0xff007b17),
      secondary: const Color(0xffccffd5),
      onSecondary: const Color(0xff004f02),
    ),
    _defaultLightBase.copyWith(
      name: "tokiwaGreen",
      iconName: "tokiwaGreen",
      primary: const Color(0xff007b45),
      secondary: const Color(0xffccffe8),
      onSecondary: const Color(0xff004f20),
    ),
    _defaultLightBase.copyWith(
      name: "hydraTurquoise",
      iconName: "hydraTurquoise",
      primary: const Color(0xff007b73),
      secondary: const Color(0xffccfffb),
      onSecondary: const Color(0xff004f3d),
    ),
    _defaultLightBase.copyWith(
      name: "peacockBlue",
      iconName: "peacockBlue",
      primary: const Color(0xff006694),
      secondary: const Color(0xffccefff),
      onSecondary: const Color(0xff00424f),
    ),
    _defaultLightBase.copyWith(
      name: "egyptianBlue",
      iconName: "egyptianBlue",
      primary: const Color(0xff0033a5),
      secondary: const Color(0xffccdbff),
      onSecondary: const Color(0xff00254f),
    ),
    _defaultLightBase.copyWith(
      name: "bohemianBlue",
      iconName: "bohemianBlue",
      primary: const Color(0xff0a00a5),
      secondary: const Color(0xffcfccff),
      onSecondary: const Color(0xff00074f),
    ),
    _defaultLightBase.copyWith(
      name: "spaceBattleBlue",
      iconName: "spaceBattleBlue",
      primary: const Color(0xff4800a5),
      secondary: const Color(0xffe2ccff),
      onSecondary: const Color(0xff16004f),
    ),
  ],
);
